# Generated by Django 4.0.5 on 2022-07-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
