# Generated by Django 4.0.5 on 2022-07-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=30, null=True)),
                ('faculty', models.CharField(max_length=255)),
                ('marks_obtained', models.IntegerField()),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('evaluation', models.CharField(max_length=255)),
            ],
        ),
    ]
