# Generated by Django 4.0.5 on 2022-06-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='City',
            new_name='city',
        ),
    ]
