# Generated by Django 4.0.5 on 2022-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0002_rename_city_studentform_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='evaluation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='faculty',
            field=models.CharField(max_length=255),
        ),
    ]
