# Generated by Django 4.0.5 on 2022-06-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0003_alter_studentform_city_alter_studentform_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
