# Generated by Django 4.0.5 on 2022-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0004_studentform_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
