# Generated by Django 4.0.5 on 2022-06-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0005_alter_studentform_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='country_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
