# Generated by Django 4.0.5 on 2022-06-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0006_studentform_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='country_code',
        ),
    ]
