# Generated by Django 4.0.5 on 2022-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0008_studentform_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
