# Generated by Django 4.0.5 on 2022-06-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0009_alter_studentform_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
