# Generated by Django 4.0.5 on 2022-06-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('street', models.IntegerField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('salary', models.BigIntegerField()),
            ],
        ),
    ]
