# Generated by Django 4.0.5 on 2022-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherform',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherform',
            name='phonenumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherform',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
