# Generated by Django 4.0.5 on 2022-06-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherform', '0002_alter_teacherform_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherform',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
