# Generated by Django 4.0.5 on 2022-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherform', '0003_rename_phonenumber_teacherform_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherform',
            name='country_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
