# Generated by Django 4.0.5 on 2022-06-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherform', '0004_teacherform_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherform',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
